### ISSUE TITLE
Spelling mistake 'coverted'

### ISSUE THREAD

**Issue by zarifaziz** [discreteoptimization/setcover#8]
Why is covered spelt as 'coverted' in the solve_it() function for the greedy folder? Took me a while to figure that out.

**Comment by zarifaziz** [comment]
Also it would be very useful if you include what type of algorithms are used for each folder in the README file

- E.g. what does 'homebrew' mean?

**Comment by ccoffrin** [comment]
I addressed the `coverted` issue, thanks!  

The folder name provides a hint on the type of algorithm that is implemented.   Homebrew means that a solver or solver framework is not used and the solver was make from scratch in the python code.
